version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: debate_database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./db/db_dump.sql:/docker-entrypoint-initdb.d/db_dump.sql
    networks:
      - app-net

  backend:
    build: ./DebateNovice
    container_name: backend
    depends_on:
      - postgres
    ports:
      - "8500:8500"
    networks:
      - app-net

  frontend:
    build: ./novice-front
    container_name: frontend
    ports:
      - "3000:80"
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
